### PR TITLE
Make ES Module

### PR DESCRIPTION
**Pull request by vwkd**
Builds spec-url as ES Module and uses import / export syntax internally, similarly to https://github.com/alwinb/reurl/pull/3

### CODE REVIEW

**Comment by alwinb** [comment]
Cool! You're ahead of me, I was planning to do this, following up on your work on reurl.

**Comment by vwkd** [comment]
Yes, a nice little side effect of me trying to play around getting reurl to run on Deno 🙃

**Comment by alwinb** [comment]
I published 1.4.0, with these changes. 

(And now realise that strictly speaking this might break semver, as the move from a commonJS module to an ES module should be considered an API change. Oh well..) 

In any case! Thank you for taking time to work on this. It all looks very tidy.

**Comment by vwkd** [comment]
Great! Also sorry for not clarifying again that it's a breaking change similar to https://github.com/alwinb/reurl/pull/3.

**Pull request merged**
